name: E2E smoke

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Install Chromium for puppeteer-core
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
      - name: Set CHROME_PATH
        run: echo "CHROME_PATH=/usr/bin/chromium-browser" >> $GITHUB_ENV
      - name: Start static server
        run: |
          cd specs/001-a4-pdf-pdf/poc
          python3 -m http.server 8000 &
          sleep 1
      - name: Run E2E
        run: npm run test:e2e
